# Generated by Django 5.2.5 on 2026-04-01 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0056_hazard_event_type_fields'),
        ('field_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(auto_now_add=True, db_index=True)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('model_count', models.PositiveIntegerField(default=0)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('adjusted_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('coverage_pct', models.FloatField(default=0.0)),
                ('confidence_pct', models.FloatField(default=0.0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_snapshots', to='datasets.cycloneevent')),
            ],
            options={
                'verbose_name': 'Confidence Snapshot',
                'verbose_name_plural': 'Confidence Snapshots',
                'ordering': ['-snapshot_date'],
                'unique_together': {('event', 'snapshot_date')},
            },
        ),
    ]
