# Generated by Django 5.2.5 on 2026-04-01 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('datasets', '0056_hazard_event_type_fields'),
        ('field_check', '0002_confidencesnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCheckAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Guidance shown to the field assessor on their mobile device.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('area_council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_check_assignments', to='datasets.areacouncil')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_field_check_assignments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('tabularitem', 'vectoritem')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('field_check_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='field_check.fieldcheckrecord')),
            ],
            options={
                'verbose_name': 'Field Check Assignment',
                'verbose_name_plural': 'Field Check Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['area_council', 'status'], name='field_check_area_co_2d40ce_idx'), models.Index(fields=['content_type', 'object_id'], name='field_check_content_7292ad_idx')],
            },
        ),
    ]
